# Generated by Django 3.1.14 on 2022-03-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
